credentials:
  usernames:
    dhkoh:
      email:inhabme@gmail.com
      first_name: donghoon
      last_name: koh
      password: Dmlrhd1!  # 실행 시 자동으로 해시 처리됩니다.
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
