credentials:
  usernames:
    inhabme:
      email: inhabme@gmail.com
      first_name: 의용공학팀
      last_name: 인하대병원
      password: inhabme
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails: []