credentials:
  usernames:
    dhkoh:
      email: dhkoh@inhauh.com
      first_name: 고동훈
      last_name: ''
      password: 3babiesfa
cookie:
  expiry_days: 30
  key: inha_med_engineering_key
  name: inha_med_session
preauthorized:
  emails: []